---
title: "Data Exploration"
output: pdf_document
---
```{r}
# libraries used
library(ggplot2)
library(dplyr)
library(ggfortify)
library(tidyverse)
```

```{r}
fish.data <- read.csv("TrawlCatch_SpringPreyfishBottomTrawl.csv")
fish.data.raw <- fish.data %>% 
  mutate(year=as.factor(year)) #didn't want year to be a continuous variable, I wanted them as discrete values not continuous.
fish.data <- fish.data.raw %>% 
  filter(!is.na(fishingTemperature_C), !is.na(latitude), !is.na(longitude), commonName!= "No fish caught", commonName!= "Miscellaneous or unidentified species", commonName!=  "Unidentified coregonid", commonName!= "Unidentified minnows",  commonName!= "Uninidentified redhorse")#I am removing any datapoints where the temperature, latitude, or longitude is not collected because they will not be useful for the questions we are asking unless we have those data
#I am also removing unidentified or misc. fishes
```


```{r}
fish.data %>% 
  group_by(commonName) %>% 
  tally() %>% 
  arrange(desc(n)) #this helped us see how many observations we had per species 
fish.list <- as.data.frame(unique(fish.data$commonName)) #this just made a data frame of the list so we could check if each one was exotic or native
fish.data.exonat <- fish.data %>% #Here we made a new column that marks each fish species as exotic or native. This was based on a few papers listed in our methods. We did not bother doing this for any fishes where there were less than 200 observations because they would not be used for this analysis anyway. We also did not do this for non-fish species as they are not the focus of this analysis. 
  mutate(inv.status = case_when(
    endsWith(commonName, "Alewife") ~ "exotic",
    endsWith(commonName, "Sea lamprey") ~ "exotic",
    endsWith(commonName, "Chinook salmon") ~ "exotic",
    endsWith(commonName, "Rainbow trout (Steelhead)") ~ "exotic",
    endsWith(commonName, "Carp") ~ "exotic",
    endsWith(commonName, "Brown trout") ~ "exotic",
    endsWith(commonName, "Rainbow smelt") ~ "exotic",
    endsWith(commonName, "Coho salmon") ~ "exotic",
    endsWith(commonName, "White perch") ~ "exotic",
    endsWith(commonName, "Blueback herring") ~ "exotic", 
    endsWith(commonName, "Chain pickerel") ~ "exotic",
    endsWith(commonName, "Round goby") ~ "exotic",
    endsWith(commonName, "Tubenose goby") ~ "exotic",
    endsWith(commonName, "Threespine stickleback") ~ "native",
    endsWith(commonName, "Emerald shiner") ~ "native",
    endsWith(commonName, "Lake whitefish") ~ "native",
    endsWith(commonName, "Deepwater sculpin") ~ "native",
    endsWith(commonName, "Lake trout") ~ "native",
    endsWith(commonName, "Burbot") ~ "native",
    endsWith(commonName, "Slimy sculpin") ~ "native",
    endsWith(commonName, "Emerald shiner") ~ "native",
    endsWith(commonName, "Cisco (lake herring)") ~ "native",
    endsWith(commonName, "Whitefishes") ~ "native",
    endsWith(commonName, "Johnny darter") ~ "native",  
    endsWith(commonName, "Trout-perch") ~ "native", 
    endsWith(commonName, "Yellow perch") ~ "native", 
    endsWith(commonName, "Spottail shiner") ~ "native"
    ))
fish.data.exonat %>% 
  filter(is.na(inv.status)) %>% 
  group_by(commonName) %>% 
  tally() %>% 
  arrange(desc(n))
#Checking to see which ones I hadn't researched yet to make sure I did not miss any important ones.
#Dreissena are mussels and we are only focused on fishes so we will be cutting those out anyway
#We ignore everything below 200 observations on this list because they do not have enough observations to be included in our data
fish.data.exonat %>%  #now that we have labeled each species, we can display our native species of interest. 
  filter(inv.status=="native") %>% 
  group_by(commonName) %>% 
  tally() %>% 
  arrange(desc(n))
#based on this, we can choose only species with more than 300 observations. In this case that means Yellow perch, Threespine stickleback, Deepwater sculpin, Trout-perch, Johnny darter, Lake trout, and Slimy sculpin.
```


```{r}
fish.data.clean <- fish.data.exonat %>% #this is now the data we are interested in, including only the species that we are able to look at.
  filter(commonName=="Yellow perch" | commonName=="Threespine stickleback" | commonName=="Deepwater sculpin" | commonName=="Trout-perch" | commonName=="Johnny darter" | commonName=="Lake trout" | commonName=="Slimy sculpin" | commonName=="Round goby")

head(fish.data.clean)
```


```{r}
unique(fish.data$year) #we have data from 1997 to 2022
#the dates should be converted into a more readable format. I just don't know how to do that so I need to ask for help.

ggplot(fish.data, aes(x=opDate, y=fishingTemperature_C)) + geom_point(alpha=0.1) + geom_smooth() + labs(title="Temperature values by date", x="Date (YYYYMMDD)", y="Temperature (Degrees C)") + theme(plot.title = element_text(hjust = 0.5)) 
```


```{r}
ggplot(fish.data.clean, aes(x=fishingTemperature_C, fill=inv.status)) + geom_histogram(bins=15) + facet_wrap(~commonName) + labs(title="Observed temperature by species", x="Temperature (Degrees C)", y="Count of individuals observed") + theme(plot.title = element_text(hjust = 0.5)) + scale_fill_discrete(name = "Status")
#plotting the count of observations of each species depending on the temperature.
```

Lets visualize the percentage of each species 
```{r}
# Proportion of the total catch from the first siting in 1997 --> 
# Based on abundance
fish.data.clean %>% 
  group_by(commonName, year) %>% 
  # filtering out year based on first time a goby was sighted --> in 1997
  filter(year %in% seq(1997, 2022)) %>% 
  tally(n) %>%  # tallying up occurances of each species
  ggplot(aes(x=year, y=n, fill=commonName)) + geom_bar(position="fill", stat="identity") + labs(title="Proportion of Catch By Species", x="Year of Study", y="Proportion of catch") + theme(axis.text.x = element_text(angle=90, hjust=1))
```


